version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package -DskipTests
      
  test: 
    docker:
      - image: cimg/openjdk:11.0

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - run: mvn test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
          
      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results/junit      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build